name: ohlcv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - black[jupyter]
  - fastparquet=2024.5.0
  - isort=5.13.2
  - jupyter=1.1.1
  - loguru=0.7.2
  - ipykernel>=6.9.0
  - lightgbm=4.5.0
  - mlforecast=0.13.4
  - mplfinance
  - numba==0.61.0
  - plotly=5.24.1
  - seaborn=0.13.2
  - statsforecast=1.7.8
  - polars=1.21.0
  - sktime==0.36.0
  - yfinance==0.2.53
