name: ohlcv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - fastparquet=2024.5.0
  - isort=5.13.2
  - jupyter=1.1.1
  - loguru=0.7.2
  - ipykernel>=6.9.0
  - lightgbm=4.5.0
  - mlforecast=0.13.4
  - plotly=5.24.1
  - seaborn=0.13.2
  - statsforecast=1.7.8
  - polars=1.21.0
  - pip:
      - yfinance==0.2.53
      - mplfinance-0.12.10b0
